### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by giacomogrande** [asielen/D3_Reusable_Charts#4]
Hello Andrew,
unfortunately I was unable to find any contact information of yours, however, as I would like to use parts of the code in a non-profit webapp, I wanted to ask your permission first. I am sorry for opening an issue but it was the only remaining option I found viable in order to get in contact with you.
Please let me know, if it is OK to use your D3_Reusable_Charts for non-profit purposes. Of yourse you will be credited in the description. 
I would be very thankful, if you could give me a short reply to giacomogrande at web.de 
Kind regards,
Jakob

**Comment by asielen** [comment]
Contacted through email.
